# Generated by Django 5.1.4 on 2024-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Sem Descrição', max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
