# Generated by Django 5.1.4 on 2024-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3),
        ),
    ]
