# Generated by Django 5.1.4 on 2024-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3),
        ),
    ]
